"""empty message

Revision ID: da84ae7aef61
Revises: 0e4f98dd037b
Create Date: 2025-07-25 11:59:20.778978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da84ae7aef61'
down_revision = '0e4f98dd037b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('homeplanet', sa.Integer(), nullable=False))
        batch_op.drop_constraint('characters_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['homeplanet'], ['id'])
        batch_op.drop_column('mass')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('birth_year')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('surface_water')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface_water', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('characters_homeworld_fkey', 'planets', ['homeworld'], ['id'])
        batch_op.drop_column('homeplanet')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
